### ISSUE TITLE
Menambahkan widget

### ISSUE THREAD

**Issue by 12200144TioFajli** [12200144TioFajli/12200144_daftarcomputer#1]
Widget yang akan ditambahkan dibuat :

1. Sidebar
2. Topbar
3. Template_Dashboard
4. Dasar_tampilan

**Comment by 12200472Irnareliawati** [comment]
Sudah beres dikerjakan boss!

**Comment by 12200472Irnareliawati** [comment]
Sudah beres saya kerjakan boss!

**Comment by 12200144TioFajli** [comment]
okee sisss
