### ISSUE TITLE
Membuat Halaman Tampilan dibagian view

### ISSUE THREAD

**Issue by 12200144TioFajli** [12200144TioFajli/12200144_daftarcomputer#4]
menambahkan folder halaman di bagian folder view yang berisi :
1. Beranda.php
2. Login.php
menambahkan folder pengguna di dalam folder halaman yg berisi file :
1. Form.php
2. table.php

**Comment by 12200061WanRiskiMaulana** [comment]
mantap bro dah selesaii ni
